[project]
name = "streaming-kafka"
version = "0.1.0"
requires-python = ">=3.12"

[tool.uv.workspace]
members = ["stream-processor"]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
